### PR TITLE
BAU Fix for the TimeZone problem in tests

### PR DESCRIPTION
**Pull request by PatrykRudnicki**

### CODE REVIEW

**Comment by PatrykRudnicki** [comment]
@SteveSugden Those tests are IT tests, I see it failed here, not sure why locally everything passed.

**Comment by SteveSugden** [comment]
So they are.  Maciej had more file changes than you though. :-)

**Comment by PatrykRudnicki** [comment]
Yeah, unit tests passed.

Now problems with the DateTimeTestModule

**Comment by PatrykRudnicki** [comment]
I forgot to merge it but probably @MaciejRewera did those changes in his PR. Closing

**Pull request closed without merging**
